version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY=admin
      - AWS_SECRET_ACCESS=admin